config/routes.rb
Rails.application.routes.draw do

  root :to => "static#index"
  get "index.html/:id" => "static#index"
  get "index.html/:sub/:id" => "static#index"
  get "index.html" => "static#index"

  resources :texts, only: [:edit, :update]

  resources :principals, only: [:edit, :update]

  resources :offers, only: [:edit, :update, :new, :create, :delete]
    get '/offers/new/:id', to: 'offers#new#id'

  resources :projects, only: [:edit, :update, :new, :create, :destroy, :show]
    get "deletephoto/:id" => "projects#deletephoto#id"

  resources :subprojects, only: [:show, :new, :create, :destroy, :edit, :update]
    get '/subprojects/new/:id', to: 'subprojects#new#id'
    get "deletepicture/:id" => "subprojects#deletepicture#id"

  resources :principals, only: [:edit, :update]

  resources :offers
    get '/offers/new/:id', to: 'offers#new#id'

  resources :contacts

  resources :user_sessions, only: [:new, :create, :destroy]
    get "logout" => "user_sessions#destroy", :as => "logout"
    get "login" => "user_sessions#new", :as => "login"

  resources :users
    get "signup" => "users#new", :as => "signup"

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  def new
    @user = User.new
  end


  def create
    if @user = login(params[:email].downcase, params[:password])
      redirect_back_or_to("/index.html")

    else
      flash[:error] = 'Login failed'
      redirect_to("/login")
    end
  end


  def destroy
    logout
      redirect_back_or_to("/index.html")
  end

end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/new.html.erb
<div id="sectioncontent2">

<h1><div class="tt">Login Administrator</div></h1>
<!--h1><tt>Login Administrator</tt></h1>
<h1>Login Administrator</h1-->
</br>
        <% flash.each do |key, value| %>
	     <div class="flash <%= key %>"><%= value %></div>
        <% end %>
</br>

<%= form_tag user_sessions_path, :method => :post do %>
<!-- form_tag sessions_path do %-->


  <div class="field">
    <%= label_tag :email %><br />
    <%= text_field_tag :email %>
  </div>
  </br>

  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  </br>

  <hr/>

  <h6>  <a href="/"> Back</a></h6>

  <div class="actions">
    <%= submit_tag "Login" %>
  </div>

<% end %>

</br>
<!-- link_to 'Back', .first -->

</div>